server {
    listen 80;

    # A frontend fájlok kiszolgálása
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

   # A minták kezelése a samples-service-hez megy
    location /api/samples {
        proxy_pass http://samples-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Az eredmények rögzítése a results-service-hez megy
    location /api/results {
        proxy_pass http://results-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /mcp/ {
    proxy_pass http://mcp-server:8000/;
    
    # A KRITIKUS SOR: Az MCP szerver a belső nevét várja el
    proxy_set_header Host mcp-server;
    
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # SSE (Streaming) beállítások
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache off;
    proxy_buffering off;
    chunked_transfer_encoding off;
    proxy_read_timeout 86400s;
}
}