server {
    listen 80;

    # A frontend fájlok kiszolgálása
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API kérések továbbítása a backend konténernek
    location /api {
        proxy_pass http://backend:5000; # A Docker hálózaton a 'backend' nevet használjuk
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}