server {
    listen 80;

    # A frontend fájlok kiszolgálása
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

   # A minták kezelése a samples-service-hez megy
    location /api/samples {
        proxy_pass http://samples-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Az eredmények rögzítése a results-service-hez megy
    location /api/results {
        proxy_pass http://results-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}