services:
  db:
    image: mongo:latest
    container_name: klab_db
    # Portot csak akkor hagyj kint, ha külső programból (pl. Compass) is látni akarod az adatbázist
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - klab-network

  # 1. Microservice: Minták kezelése (Regisztráció, Lista)
  samples-service:
    image: ghcr.io/laislo/klab-samples-service:latest
    labels:
      - "com.containrrr.watchtower.enable=true"
    build: ./samples-service
    container_name: klab_samples_service
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
    networks:
      - klab-network

  # 2. Microservice: Eredmények és OOS logika
  results-service:
    image: ghcr.io/laislo/klab-results-service:latest
    labels:
      - "com.containrrr.watchtower.enable=true"
    build: ./results-service
    container_name: klab_results_service
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
    networks:
      - klab-network

  # 3. MCP Szerver: Független AI interfész
  mcp-server:
    image: ghcr.io/laislo/klab-mcp-server:latest
    labels:
      - "com.containrrr.watchtower.enable=true"
    build: ./mcp-server
    container_name: klab_mcp_server
    ports:
      - "8080:8000"
    environment:
      - SAMPLES_API_URL=http://samples-service:8000
      - RESULTS_API_URL=http://results-service:8000
      - PYTHONUNBUFFERED=1
      - ENV=production
    depends_on:
      - samples-service
    networks:
      - klab-network

  # Frontend: Nginx proxy-val az elején
  frontend:
    image: ghcr.io/laislo/klab-frontend:latest
    labels:
      - "com.containrrr.watchtower.enable=true"
    build: ./frontend
    container_name: klab_frontend
    ports:
      - "80:80"
    depends_on:
      - samples-service
      - results-service
    networks:
      - klab-network

    watchtower:
    image: containrrr/watchtower
    container_name: klab_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Milyen gyakran ellenőrizzen (másodpercben). Pl. 300 mp = 5 perc
      - WATCHTOWER_POLL_INTERVAL=300
      # Csak azokat a konténereket frissítse, amiket megjelölünk (biztonságosabb)
      - WATCHTOWER_LABEL_ENABLE=true
      # Ha a GitHub Registry (GHCR) privát, ide kellenek a belépési adatok
      # - WATCHTOWER_HTTP_API_UPDATE=true
      # - REPO_USER=${GITHUB_USER}
      # - REPO_PASS=${GITHUB_TOKEN}
    restart: always

volumes:
  mongo_data:

networks:
  klab-network:
    driver: bridge