services:
  db:
    image: mongo:latest
    container_name: klab_db
    ports:
      - "27017:27017"

  backend:
    image: ghcr.io/laislo/klab-backend:main
    container_name: klab_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db

  frontend:
    image: ghcr.io/laislo/klab-frontend:main
    container_name: klab_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
