### Alapváltozók beállítása
@baseUrl = http://192.168.1.60/api

# Ide másold majd be az első POST kérés után kapott _id értéket!
@sampleId = 69eb44653ef112eaeb43c500

### 1. Új minta létrehozása (SAMPLES SERVICE)
# @name createSample
POST {{baseUrl}}/samples
Content-Type: application/json

{
    "drugName": "Aspirin 100mg",
    "batchNumber": "ASP-2026-999",
    "specMin": 98.0,
    "specMax": 102.0
}

### 2. Összes minta lekérése (SAMPLES SERVICE)
GET {{baseUrl}}/samples

### 3. Egy konkrét minta lekérése (SAMPLES SERVICE)
GET {{baseUrl}}/samples/{{sampleId}}

### 4. Mérés rögzítése (RESULTS SERVICE)
# Figyelem: Ez a kérés az Nginx-en keresztül a Results Microservice-hez fut be!
PATCH {{baseUrl}}/results/{{sampleId}}
Content-Type: application/json

{
    "assayValue": 99.5
}

### 5. Minta törlése (SAMPLES SERVICE)
DELETE {{baseUrl}}/samples/{{sampleId}}

### --- MCP SZERVER ELLENŐRZÉSE (Opcionális) ---
GET http://192.168.1.60:8080/sse