apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: klab
spec:
  selector:
    app: mcp-server
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
